### ISSUE TITLE
module-info.class for jmod files is not recognize

### ISSUE THREAD

**Issue by khmarbaise** [codehaus-plexus/plexus-languages#1]
Inside a jmod file the `module-info.class` is located in `classes/module-info.class`.

**Comment by rfscholte** [comment]
Confirmed: from [JEP-261](http://openjdk.java.net/jeps/261)

> A module path is a sequence, each element of which is either a module definition or a directory containing module definitions. Each module definition is either
> * A module artifact, i.e., a modular JAR file or a JMOD file containing a compiled module definition, or else
> * An exploded-module directory whose name is, by convention, the module's name and whose content is an "exploded" directory tree corresponding to a package hierarchy.

**Comment by khmarbaise** [comment]
@rfscholte Do you have a more elegant way for implementing this ? I'm currently testing this in relationship with maven-jlink-plugin and it works that way...If you are ok with the current implementation I would like to make a new release of it...to have version which supports jmod files as well..

**Comment by rfscholte** [comment]
Looks good to me. I will need a new release for surefire

**Comment by khmarbaise** [comment]
Ok. I will merge to the master ...would you like to make a release or should I do so?

**Comment by rfscholte** [comment]
Go ahead!

**Comment by khmarbaise** [comment]
Ok...I will do so...
