### ISSUE TITLE
Upgrade ASM version 6.1.1

### ISSUE THREAD

**Issue by khmarbaise** [codehaus-plexus/plexus-languages#12]
Upgrade to 6.1.1 version of ASM

**Comment by sormuras** [comment]
👍

**Comment by Tibor17** [comment]
@khmarbaise 
You already made a release 16 hours ago. We can use it.

**Comment by khmarbaise** [comment]
@Tibor17 I have only upgraded the asm dependency cause you seemed to need it...Are there other issues you need ?

**Comment by Tibor17** [comment]
@khmarbaise 
I expected release vote on ML. Because it did not come I guessed there are some pending issues more you want to have in the version as well.
