### ISSUE TITLE
Feature: Detection of the Java Class File version

### ISSUE THREAD

**Issue by jorsol** [codehaus-plexus/plexus-languages#147]
Sometimes it might be useful to have a way to read the class file version of a compiled class to know which version of Java was used to compile that class.

One example of such use case is in the maven-compiler-plugin, where it should be possible to detect the class file version of a previous compilation and compare it with the current version of the target/release, this way it allows to detect if the class needs recompilation or not.

**Comment by rfscholte** [comment]
It looks like with the classfile api it will be as easy as

    ClassModel classModel = ClassModel.of(bytes);
    int majorVersion = classModel.majorVersion();
    int minorVersion = classModel.minorVersion();

There's no target release yet, so it makes sense to add something similar. With a multirelease jar we can also redirect to the official class-api.
