### ISSUE TITLE
NullPointerException on pom  in plexus-java 0.9.10

### ISSUE THREAD

**Issue by mwolfthal** [codehaus-plexus/plexus-languages#20]
If `<dependencies>` contains a `<type>pom</type>` this call:

`moduleDescriptor = binaryParser.getModuleDescriptor( path );`

**Comment by mwolfthal** [comment]
If `<dependencies>` contains a `<type>pom</type>` or `<type>war</type>` this call:
`moduleDescriptor = binaryParser.getModuleDescriptor( path );`
throws an` IOException:`
`zip END header not found`
because the file is being treated as a jar file. 
When the call returns to `CompilerMojo.preparePaths()` this call returns null:
`Throwable cause = pathException.getValue().getCause();`
and the next line throws a `NullPointerException`:
`while ( cause.getCause() != null )`

**Comment by mwolfthal** [comment]
posted to jira as well

**Comment by rfscholte** [comment]
Won't fix. `LocationManager` will only handle valid classpath/modulepath elements, any other element will result in an exception. It is up to the consuming code (in this case maven-compiler-plugin) to provide the right set of files.

**Comment by mwolfthal** [comment]
Fine, but that doesn't mean an exception should be added just because every file is silently assumed to be a zip file.

**Comment by rfscholte** [comment]
What's the alternative? Valid classpath/modulepath elements are either zip files or directories. The consuming code must decide what to do with the exception, and that might be simply ignoring it.

**Comment by mwolfthal** [comment]
An alternative would be, if zip parsing fails, a more informative exception  message such as “foo-pom.xml” is not a supported file type”

 

Marvin Wolfthal

email: maw@weichi.com

**Comment by rfscholte** [comment]
The consuming code can already extract that information, the Exception is mapped to its resource.

**Comment by mwolfthal** [comment]
But isn’t the error message misleading when the target file is not a zip?

 

Marvin Wolfthal

email: maw@weichi.com

**Comment by rfscholte** [comment]
The best I can do is: any regular file with an extension != "jar" will get an IllegalArgumentException. This might be good enough, modules can only be directories and jars. But the specification also says that zip files are valid classpath elements. Don't think this is used much, so that could be solved once somebody hit that issue.
