### ISSUE TITLE
Use the Java 9 API to parse module descriptors

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-languages#5]
Hi,

What do you think about the idea to make Plexus Java multi-release JAR so on Java 9+ it uses the APIs provided by Java SE. For example now if you compile module A on Java 10 and use Maven to compile B that depends on A, it will fail because ASM is not compatible with the new class format introduced with Java 10.

**Comment by rfscholte** [comment]
MRJars are kind of terrible to maintain and test. It should be possible to implement it while keeping source+target on 7 and just put it under `src/main/java`. At runtime you can look for a certain class to decide if ASM should be used or the Java9 API.

**Comment by rfscholte** [comment]
Let's pick this up. This should make it possible to use EA versions of Java without having to wait for ASM. We've already been hit by Java 10 and 11...

**Comment by rfscholte** [comment]
@plamentotev what about this? My IDE doesn't like it, but Maven does. Just need to ensure to use at least Java9 when releasing.

**Comment by plamentotev** [comment]
Sorry, my bad I meant to say "If the BinaryModuleInfoParserTest is executed in the integration-test phase by Failsafe...", not "...by Surefire...". Failsafe uses the Jar file created during the `package` phase so `java` picks up the correct class. The following configuration tests the proper class:

```
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-failsafe-plugin</artifactId>
      <version>2.21.0</version>
      <executions>
        <execution>
          <goals>
            <goal>integration-test</goal>
            <goal>verify</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <includes>
            <include>**/*Test.java</include>
            <include>**/IT*.java</include>
            <include>**/*IT.java</include>
            <include>**/*ITCase.java</include>
        </includes>      
      </configuration>
    </plugin>
```
There are some test failures though.

**Comment by rfscholte** [comment]
I wanted to reuse the configuration of surefire during integration-test and even noticed differences between the 2 runs. But the result was indeed misleading, failsafe is the preferred solution. Now it is looking much better.
For me the benefits of turning this into a multirelease jar are more compared to the IDE struggles and the reflection approach we had to do if we don't want do depend on ASM.
Main thing for me: no need to catch up with every new Java release.

**Comment by plamentotev** [comment]
@rfscholte I agree with you. I was concerned about the tests but now looks good to me.

**Comment by plamentotev** [comment]
Also I wonder if we can use the enforcer plugin to ensure that at least JDK 9 is used during a release(to avoid releasing without the Java 9 classes by mistake).

**Comment by rfscholte** [comment]
That idea crossed my mind as well. There are only a few that will release this library and they all know about it, so we should be good. But just in case: let's add a release-profile, just to be sure.

**Comment by plamentotev** [comment]
Yes, looks great.
