### ISSUE TITLE
16-ea is not 'atLeast("16")'

### ISSUE THREAD

**Issue by bmarwell** [codehaus-plexus/plexus-languages#51]
JDK identifying as `16-ea` does not satisfy `.isAtLeast("16")`.

This makes it impossible to test some maven plugins early using ea-versions.

**Comment by rfscholte** [comment]
This is similar to the -SNAPSHOT discussion. According to https://github.com/codehaus-plexus/plexus-languages/blob/6c09c078c7ea89037f67fb599778d312637642e1/plexus-java/src/test/java/org/codehaus/plexus/languages/java/version/JavaVersionTest.java#L66-L69 9-ea is before 9.
Most likely you're not testing the java version, but the implementation version, in which case you should use https://codehaus-plexus.github.io/plexus-languages/plexus-java/apidocs/org/codehaus/plexus/languages/java/version/JavaVersion.html#JAVA_SPECIFICATION_VERSION
