### ISSUE TITLE
Collect exceptions caused by unzipping non-jars (e.g. pom.xml)

### ISSUE THREAD

**Issue by rfscholte** [codehaus-plexus/plexus-languages#9]
https://issues.apache.org/jira/projects/MCOMPILER/issues/MCOMPILER-327 shows an issue where a `pom.xml` is (ab)used as some sort of container to put dependencies on the classpath. `javac` simply ignores that file, put it can be passed as argument.
The locationManager should be able to handle such situations.

**Comment by mwolfthal** [comment]
The use of pom dependencies is not an abuse - it is a way of grouping multiple related dependencies in a BOM (bill of materials)
